### ISSUE TITLE
Support unpacking for computed vars

### ISSUE THREAD

**Issue by ElijahAhianyo** [reflex-dev/reflex#1328]
we should be able to support doing something like this:

```python
class State(rx.State):
    @rx.var
    def values()-> List[str]: # or replace with Tuple
       return [1, 2, 3, 4]
    
 def index():
    a, b, c, d = State.values
    ...

```

**Comment by masenf** [comment]
it should be possible if we implement `__iter__` for `BaseVar` to return additional `BaseVar` instances that dereference the original value at some index, but where to stop? the iterator has no idea what's on the left-hand side.

i think a syntax where we take a slice with known indicies would be much more amenable to unpacking.

```python
 def index():
    a, b, c, d = State.values[:4]
    ...
```

It's still not perfectly safe, because the list could have less than 4 items, and then it would blow up in the frontend code which is much harder to diagnose and handle.

**Comment by picklelo** [comment]
I think this will be a bit tricky in the general case. Closing for now.
