### ISSUE TITLE
I can't use reflex command after I install it

### ISSUE THREAD

**Issue by z369437558** [reflex-dev/reflex#1414]
I'm so sorry for my simple problem
I install this project by using "pip install reflex --user"
because I don't have the admin right so I have to add the --user
by that I install this project successfully.
but when I want to use the reflex init  it's said that The term 'reflex' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by ElijahAhianyo** [comment]
can you confirm if youre running in a virtual environment(venv, poetry, conda, etc)?
Also, since youre installing with the `--user` flag, make sure the directory containing your user-specific python and pip executables are added to the `PATH` environment variable

**Comment by masenf** [comment]
an alternative approach is to use a virtualenv, then `activate` the virtualenv which should temporarily fix the `PATH` in your terminal to be able to see the `reflex` command.

Yet another alternative approach is to invoke reflex via `python -m reflex.reflex` (and when #1516 merges, just `python -m reflex`).

Otherwise, you'll need to ensure that your user scripts directory is on the path. I'm assuming based on the error message that you're on windows platform.

Here are some basic instructions for adding your user python script path to the windows path:

1. run `python -m site` to dump out the paths used by your python interpreter. You're looking for `USER_SITE`.
2. replace `site-packages` with `Scripts` to get the user script path. On my system, it's something like `C:\\Users\\masenf\\AppData\\Roaming\\Python\\Python311\\Scripts`
3. Follow instructions [here](https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/) to edit environment variables on windows. You want to add the script path to your user `PATH` variable.

I'm going to close this issue for now, but feel free to reopen or file additional issues if you are still stuck.
