### ISSUE TITLE
Add debouncing for slider components

### ISSUE THREAD

**Issue by picklelo** [reflex-dev/reflex#1482]
#1383 forces inputs and textareas to be uncontrolled, and lets you use `rx.debounce_input` to make them controlled. We should support a similar method for sliders. Maybe we can rename the component to `rx.debounce` and have it generalize to all components?

**Comment by masenf** [comment]
Not so sure about this one. We already expose `on_change_start` and `on_change_end` and describe those pretty well in the docs. I'm not sure what debounce would add to those existing event handlers.

If you think those are fine, then we should close this issue @picklelo.

**Comment by dodeca-6-tope** [comment]
@masenf it's true that there are "discrete" handlers already but I believe generalizing this component like suggested would improve UX. I'm thinking about dropping this component in my app just because it lags on the frontend.

**Comment by dodeca-6-tope** [comment]
Is there a way to continuously update slider value on the frontend and debounce on the backend? Currently there is a lag on the frontend (also on the [slider page](https://reflex.dev/docs/library/forms/slider/)). I think such enhancement can improve UX a lot.

**Comment by masenf** [comment]
> Is there a way to continuously update slider value on the frontend and debounce for the backend?


There isn't a _nice_ way to do it.

We've considered an idea for first class "frontend state" where values can be stored entirely in the browser without roundtripping to the backend, but it complicates the overall design of reflex and we haven't gone forward with it intentionally.

It's hackable though, if you're okay getting your hands dirty. And thanks to recent changes in the reflex compiler, it's actually not too nasty to implement:

Essentially we have to create our own `rx.Var` which is tied to react's `setState` hook to create local state, and another `rx.Var` which can act as the event handler for `on_change` to set the local state value.

The last piece of the puzzle is this weird `IntegralFragment` which inherits from `MemoizationLeaf`, meaning that it and all it's children will NOT be separated into their own react components; this allows all of the components inside the `IntegralFragment` to access the same `local_slider_value` variable.

```python
import reflex as rx
from reflex.components.component import MemoizationLeaf
from reflex.utils import imports


class State(rx.State):
    val: int = 50
    

LOCAL_SLIDER_VALUE = "local_slider_value"
SET_LOCAL_SLIDER_VALUE = "set_local_slider_value"
LOCAL_SLIDER_VAR_DATA = rx.vars.VarData(
    imports={"react": {imports.ImportVar(tag="useState")}},
    hooks={f"const [{LOCAL_SLIDER_VALUE}, {SET_LOCAL_SLIDER_VALUE}] = useState(50);"},
)
LOCAL_SLIDER_VAR = rx.Var.create(LOCAL_SLIDER_VALUE)._replace(
    _var_type=int,
    merge_var_data=LOCAL_SLIDER_VAR_DATA,
)
LOCAL_SLIDER_ON_CHANGE = rx.Var.create(
    f"e => {SET_LOCAL_SLIDER_VALUE}(e)"
)._replace(
    _var_type=rx.EventChain,
    merge_var_data=LOCAL_SLIDER_VAR_DATA,
)


class IntegralFragment(rx.Fragment, MemoizationLeaf):
    """All children of this component will be rendered as a single react component."""


def index() -> rx.Component:
    return rx.fragment(
        rx.color_mode_button(rx.color_mode_icon(), float="right"),
        rx.vstack(
            rx.heading(f"Backend Value: {State.val}"),
            IntegralFragment.create(
                rx.heading(f"Frontend Value: ${{{LOCAL_SLIDER_VAR}}}"),
                rx.slider(
                    value=LOCAL_SLIDER_VAR,
                    on_change=LOCAL_SLIDER_ON_CHANGE,
                    on_change_end=State.set_val,
                ),
            )
        ),
    )


app = rx.App()
app.add_page(index)
app.compile()
```

This produces the following react component

```javascript
export function Fragment_2cb080c4510d19d553f6cbe861899f44 () {
  const [local_slider_value, set_local_slider_value] = useState(50);
  const [addEvents, connectError] = useContext(EventLoopContext);


  return (
    <Fragment>
      <Heading>
      {`Frontend Value: ${local_slider_value}`}
      </Heading>
      <Slider onChange={e => set_local_slider_value(e)} onChangeEnd={(_e0) => addEvents([Event("state.state.set_val", {value:_e0})], (_e0), {})} value={local_slider_value}>
      <SliderTrack>
        <SliderFilledTrack/>
      </SliderTrack>
      <SliderThumb/>
    </Slider>
  </Fragment>
  )
}
```

This approach isn't perfect though... for example if you tried to set `self.val` from an event handler, it would not be reflected in the frontend, because the slider value is tied to the local state. So `State.val` is essentially read-only in this arrangement, maybe that's okay. To make it bidirectional is possible, in theory, but significantly harder to implement.

**Comment by picklelo** [comment]
Recommended approach is to use the `throttle` and `debounce` options now.
