### ISSUE TITLE
icon prop in `rx.icon_button`  doesnt work

### ISSUE THREAD

**Issue by ElijahAhianyo** [reflex-dev/reflex#1497]
icon prop should take a component. Also providing string values doesnt work

**Comment by andrewbantly** [comment]
I noticed that when passing props to the IconButton Component, an `Invalid ARIA attribute` error is prompted:

`rx.icon_button(aria_label="Send email", icon="email")`
> client.js:1 Warning: Invalid ARIA attribute `ariaLabel`. Did you mean `aria-label`?

Perhaps there is a syntax error fails to recognize the Chakra IconButton?

**Comment by andrewbantly** [comment]
@ElijahAhianyo To clarify, you want to see text & an icon inside a `rx.icon_button`? I was reading the Chakra documentation there appears to be a disconnection in the usage:

>**[Usage](https://chakra-ui.com/docs/components/icon-button/usage#usage)**
IconButton composes the Button component except that it renders only an icon. Since IconButton only renders an icon, you must pass the aria-label prop, so screen readers can give meaning to the button.

Thank you and I hope to get this issue resolved soon.

**Comment by picklelo** [comment]
The new `rx.icon` component is based on Lucide and should work better.
