### ISSUE TITLE
on_click Broken for Button Components

### ISSUE THREAD

**Issue by jparr721** [reflex-dev/reflex#1514]
**Describe the bug**
When running `reflex init --template counter` and then `reflex run` the resultant application has buttons, but none of them work. In fact, even when I roll my own app, none of the buttons are capable of calling into the state handler.

**To Reproduce**
- `reflex init --template counter`
- `reflex run`

**Expected behavior**
I expect the buttons to work.

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version: 3.11.4
 - Reflex Version: 0.2.3
 - OS: MacOS
 - Browser (Optional): Safari
 
**Additional context**

**Comment by jparr721** [comment]
There are, but I am honestly not sure why. I've run plenty of apps before without issue on safari, even NextJS itself. Is there something within the framework that is causing a problem?

**Comment by ElijahAhianyo** [comment]
what does your rxconfig.py file look like?

**Comment by jparr721** [comment]
I'm just using the one that was default generated.

```python
import reflex as rx


class ProjectNameConfig(rx.Config):
    pass


config = ProjectNameConfig(
    app_name="name",
    db_url="sqlite:///reflex.db",
    env=rx.Env.DEV,
)
```

**Comment by curator4356** [comment]
Facing the same issue here also

getting
`WebSocket connection to 'ws://localhost:8000/event/?EIO=4&transport=websocket' failed: `

in console

**Comment by eldjoko** [comment]
Facing the same issue. the `on_click` event handler is not working, hence none of the button functions perform the actions needed. Tried to console log the event when clicked but nothing happens.

The WS connection also fails displaying the following message:

![image](https://github.com/reflex-dev/reflex/assets/10700361/bb7d697d-2e95-465a-b81c-f4345bdfc2f1)

![image](https://github.com/reflex-dev/reflex/assets/10700361/36b236c2-3a6d-4773-aece-c52f29b44177)

This issue is related to #1796 which i opened myself.
