### ISSUE TITLE
weird behaviour of on_load with lambda functions

### ISSUE THREAD

**Issue by Anga205** [reflex-dev/reflex#1574]
**Describe the bug**
while lambda functions work perfectly with event triggers like on_click and on_blur, they break with on_load

**To Reproduce**
here, the button prints to terminal when clicked-
```py
import reflex as rx


class State(rx.State):
    def print_data(self, data):
        print(data)


def index() -> rx.Component:
    return rx.button("click me!", on_click=lambda e: State.print_data("clicked!"))

app = rx.App()
app.add_page(index)
app.compile()
```

here, the page does not print to terminal when loaded

```py
import reflex as rx


class State(rx.State):
    def print_data(self, data):
        print(data)


def index() -> rx.Component:
    return rx.button("click me!", on_click=lambda e: State.print_data("clicked!"))

app = rx.App()
app.add_page(index, on_load=lambda:State.print_data("loaded!"))
app.compile()
```

**Comment by masenf** [comment]
Thank you for filing this issue. I have an idea for a fix here 💡:

Currently `on_load` is handled by middleware, but I can move `on_load` event handling into the "initial events" array compiled into the page, which would cause it to be handled just like any other frontend event, like `on_click`.

Here is where the events are added to the `initial_state`: https://github.com/reflex-dev/reflex/blob/56ab2bb0125bef4bcd2ca3538a4d4d7525f93334/reflex/compiler/utils.py#L132

And here is where that `initial_state` is compiled into the page: https://github.com/reflex-dev/reflex/blob/56ab2bb0125bef4bcd2ca3538a4d4d7525f93334/reflex/compiler/compiler.py#L93

So if we can add in the `on_load` events in either of those places and remove them from middleware [here](https://github.com/reflex-dev/reflex/blob/56ab2bb0125bef4bcd2ca3538a4d4d7525f93334/reflex/middleware/hydrate_middleware.py#L49), then i think this can just start to work. 😄

**Comment by Anga205** [comment]
is there any _other_ way to force a function (with attributes) to run when a page is loaded that doesnt require me to significantly meddle with reflex's compiler?

**Comment by masenf** [comment]
> is there any other way to force a function (with attributes) to run when a page is loaded

```python
import reflex as rx


class State(rx.State):
    foo: str = "not loaded"

    def on_load(self, arg):
        print("on_load")
        self.foo = f"loaded with {arg!r}"


class OnLoadHack(rx.Fragment):
    def _get_hooks(self):
        formatted_on_load = rx.components.tags.tag.Tag.format_prop(
            self.event_triggers["on_load"]
        )[7:-6] + ")"
        return f"""
        useEffect(() => {{
            {formatted_on_load}
        }}, [])
        """

    def get_triggers(self):
        return super().get_triggers() | {"on_load"}

    def render(self) -> str:
        return ""


def index():
    return rx.fragment(
        OnLoadHack.create(on_load=lambda: State.on_load("via hack")),
        rx.text(State.foo),
    )


app = rx.App()
app.add_page(index)
app.compile()
```

I wasn't necessarily suggesting you to meddle with the compiler (unless you like to 🙏). I was just leaving a note for myself or other maintainers to understand how to fix this for when we're able to get to it.

In the meantime, feel free to hack away and make it work with the above snippet. You'll notice that this actually fires the event _twice_ in dev mode, this is due to react strict mode; technically `useEffect` shouldn't have out of band side-effects like that, but we're hacking to make it work, so it is what it is.

**Comment by Anga205** [comment]
thank you!

**Comment by Anga205** [comment]
as of reflex 0.2.5 this solution no longer works, is there any other way to achieve this aside from permanently being on reflex 0.2.4?

**Comment by masenf** [comment]
This change is needed: https://github.com/reflex-dev/reflex/pull/1636/files#diff-454b1ec62b97bb9007f1f01e915ac02ec44d8deefad71c376d7496e149477e3e

But when that PR lands, you won't need to use the hack anymore, you can just use `on_mount` directly, which will support lambda functions.

That PR is expected to land this week and be released next week in 0.2.7.

Sorry for the inconvenience.

**Comment by Anga205** [comment]
on_mount is not covered in the documentation, is it going to be similar to the on_load event trigger? or will its usage be closer to the loadhack syntax

**Comment by masenf** [comment]
The docs for it haven't been written yet.

`on_mount` and `on_unmount` will be exposed on every component, and they accept any type of event handler that will be triggered client-side when the javascript code starts running; so it will be _exactly_ like the `OnLoadHack`, since it's implemented in the same way, using `useEffect()`. (writing the `OnLoadHack` was the inspiration for generalizing and implementing `on_mount`).

You will need a component to attach the `on_mount` to, but it can be an `rx.fragment` or `rx.vstack` or any other top-level component on your page. The other difference is that `on_mount` will be composable, so if you define it in a "helper component" and then include that on multiple pages, then you'll get the event to trigger on every page it's included in (unlike `on_load` which must be attached to every page explicitly in `app.add_page`).

`on_load` is kind of a weird event trigger in that it is handled exclusively on the backend, so it doesn't have access to client-side events like `rx.console_log` and it cannot support lambdas (and probably other limitations).

**Comment by Anga205** [comment]
using on_mount with lambda functions yeilds the exact same error as the on_load function

my implementation of it was, in ur sample code, i replaced `OnLoadHack.create(on_load=lambda: State.on_load("via hack"))` with `on_mount=lambda: State.on_load("via hack")`


and it gave me the error:

`TypeError: Could not format prop: {'onMount': <function login.<locals>.<lambda> at 0x0000025A8B72E480>} of type <class 'reflex.style.Style'>`

**Comment by masenf** [comment]
@Anga205 are you running on the `masenf/on_mount` branch?

```console
pip install git+https://github.com/reflex-dev/reflex@masenf/on_mount
```

As I said previously,

> **But when that PR lands**, you won't need to use the hack anymore, you can just use on_mount directly, which will support lambda functions.

PR #1636 hasn't merged yet, but when it does, you'll be able to just apply `on_mount` to a fragment, and get rid of the `OnLoadHack` component entirely.

**Comment by Anga205** [comment]
my bad, i have changed my reflex version to the masenf/on_mount branch and it works now, thanks for the help!, ill be waiting eagerly for reflex 0.2.5 ig

**Comment by Anga205** [comment]
on_mount works when i run my app on `reflex run` however it throws the same type error when i run it with `reflex run --env prod`

**Comment by Anga205** [comment]
importing mansef/on_mount no longer works as of today

**Comment by masenf** [comment]
Can you elaborate on what "no longer works" means? are you seeing an error? the events don't fire?

I haven't pushed any changes to that branch, so I'm not sure how it could have broken.

Also, that PR merged to `main`, so you should be able to run against the `main` branch now to test out the latest changes going into 0.2.7.

**Comment by Anga205** [comment]
this is what i mean:
![image](https://github.com/reflex-dev/reflex/assets/74541474/9eb1eb8c-3fc7-40f9-a17e-3d76393444b6)


also pip instlaling reflex installs 0.2.6 as i dont think 0.2.7 is out on pypi yet

**Comment by masenf** [comment]
ah, i see. i must have deleted the branch after it merged;

you can either install from the `main` branch, which has the change now. or you can continue to install directly from the ref f416413d9e3bbbb9cb18b78daf781e3620133fc1

with `pip install git+https://github.com/reflex-dev/reflex@f416413d9e3bbbb9cb18b78daf781e3620133fc1`
