### ISSUE TITLE
Cannot get text smoothly from function that passed through foreach

### ISSUE THREAD

**Issue by rlawjdgh2218** [reflex-dev/reflex#1601]
```python
import reflex as rx


def table_put_data_user(in_dict):
    id_text = in_dict['test'] + '_id_test'
    print(id_text)  # the result is like this: {(rzcnfrzo["test"] + "_id_test")}

    rx.input(value=in_dict['test'], width="50%", text_align='center', is_read_only=True, id=id_text, size="60%")


class State(rx.State):
    user_data_list: List[Dict[str, str]] = [{'test': 'test1'}, {'test': 'test2'}]
    form_data_list = []

    def user_data_foreach(self, form_data: dict):
        print(form_data)  # No id being output because foreach doesn't read the variable.
        self.form_data_list.append(form_data)


@rx.route(route="/test-main", title='test main')
def test_main():
    rx.vstack(
        rx.form(
            rx.hstack(
                rx.center(
                    rx.button("button", type="submit", bg="lightblue", size="60%")

                )),
            rx.foreach(State.user_data_list, table_put_data_user)),
        on_submit=State.user_data_foreach)


app = rx.App(State)
app.compile()
``` 

Cannot get text smoothly from function that passed through foreach

**Comment by masenf** [comment]
It's not possible to print a dynamic frontend value in the python code like that since `table_put_data_user` runs at compile time to generate the javascript for the page.

you could however have something like `on_mouse_enter=rx.console_log(id_text)` as part of the `rx.input` and then when you mouse over the input box, the browser console will log the value.

the real underlying problem here is that the `rx.form` depends on refs being created for each input element in the form, and when you're using `rx.foreach`, the id is a dynamic variable and thus no ref can be created for it.

to fix this issue will take some significant refactoring to enable dynamic values to be used as refs.

**Comment by masenf** [comment]
The fix for this issue is to use `name` prop in the `rx.input` instead of `id` when the value is dynamically created. Working in 0.5.3
