### ISSUE TITLE
min_steps_between_thumbs not work in slider

### ISSUE THREAD

**Issue by ltm920716** [reflex-dev/reflex#1632]
**Describe the bug**
param ’min_steps_between_thumbs‘ not work in rx.slider

**To Reproduce**
```
rx.slider(                           
        min_steps_between_thumbs=10,
        id="api_temperature",
        on_change_end=State.set_node_temperature,
    ),
```

**Expected behavior**
step 10.

**Screenshots**
![image](https://github.com/reflex-dev/reflex/assets/12007227/09d2412e-e1ec-4af7-814a-0eaf24588a65)

**Comment by masenf** [comment]
`min_steps_between_thumbs` is intended to keep a slider with multiple thumbs from having overlapping values... but it looks like it was actually removed from chakra-ui (the component library that reflex wraps).

At any rate, it would not have any effect unless creating a slider with multiple thumbs (the thing you grab and slide along the track).

What is your intended behavior? It sounds like you want the slider to move in steps of 10... that would be the `step` prop, which seems to not be exposed... but you can always hack around unexposed props via the `custom_attrs` escape hatch.

```python
import reflex as rx


class State(rx.State):
    v: int = 50


def index() -> rx.Component:
    return rx.container(
        rx.text(State.v),
        rx.slider(
            default_value=State.v,
            on_change_end=State.set_v,
            custom_attrs={"step": 10}
        ),
        width="40vw",
    )


# Add state and page to the app.
app = rx.App()
app.add_page(index)
app.compile()
```

I think we can definitely get the `step` prop added to the component as an actual prop, if that solves your issue. 

And we should get the `min_steps_between_thumbs` prop removed, since it doesn't seem to work anymore.

Let me know if this sounds reasonable.

**Comment by ltm920716** [comment]
Hi @masenf ，
Great！ ’custom_attrs‘ works！It is very useful, thanks!
