### ISSUE TITLE
[REF-552] Reflex prints warning about Node binary not found

### ISSUE THREAD

**Issue by masenf** [reflex-dev/reflex#1778]
Running `reflex init` inside a fresh `python:3.11` docker contain prints the following warning twice

```
Warning: The path to the Node binary could not be found. Please ensure that Node is properly installed and added to your system's 
PATH environment variable.
```

Which doesn't really make sense, because then it goes and bootstraps a version of node, which it then proceeds to use.

This warning should only be displayed if node is not installed, and Reflex is unable to bootstrap a version.

Present in 0.2.7a3

<sub>From [SyncLinear.com](https://synclinear.com) | [REF-552](https://linear.app/reflex-dev/issue/REF-552/reflex-prints-warning-about-node-binary-not-found)</sub>

**Comment by Billa05** [comment]
I have made some changes, now how to verify changes locally?

**Comment by sgopalan98** [comment]
Hi @masenf 

I looked at the source code for the problem that you mentioned. This is my understanding.

"reflex init" installs bun and node using `processes.new_process` function (called one time for each of their installation) https://github.com/reflex-dev/reflex/blob/701970863830c735e342a853340be1edd628f6ef/reflex/utils/processes.py#L116-L134

In this function, node's bin path is fetched in order to be added to the PATH variable, and if node isn't installed, the warning that you mentioned is thrown. 

Since python3:11 docker image doesn't have node installed by default, and we need to install node using fnm zip, it makes sense for the initial calls to install bun and node to throw these warnings (as these installation is done through processes.new_process).

So, I feel that this warning makes sense - as until we install node, the warning needs to be thrown... Your thoughts on this?
