### ISSUE TITLE
Generate static convenience methods for all components

### ISSUE THREAD

**Issue by Alek99** [reflex-dev/reflex#1865]
We're currently generating .pyi files for type hinting in IDEs, and it would also be nice to generate the `__init__.py` files inside `reflex/components` that expose the `ComponentX.create` functions as `component_x`.

We have this bit of code commented out:

https://github.com/reflex-dev/reflex/blob/2f284a08b6afabd1d3141830d846b7c934fccf1f/reflex/components/__init__.py#L18-L25

But this approach actually breaks our IDE integration, because we need to statically link the `snake_case` component name to the `Component.create` function for the IDE to find the pyi type hints.

To solve this issue the `pyi_generator` (or a new generator) needs to exist that scans through component modules, and creates a hierarchy of `__init__.py` files similar to the ones we already have in https://github.com/reflex-dev/reflex/blob/main/reflex/components/__init__.py

**Comment by adkbbx** [comment]
Hey, I am intersted in contributing to this issue do let me know how I can help.

**Comment by picklelo** [comment]
@adkbbx Pretty much we want to remove all the manual redefinitions within that file. For example the lines that say `box = Box.create`. And replace it with the commented code. We had to do the manual work because the definitions weren't getting picked up by IDEs before, but now we generate `.pyi` files that define the signatures, so we don't need to do this anymore.

**Comment by y9rabbito** [comment]
@Alek99 @adkbbx and others you could review that and see if it's alright or whether any changes are needed.

**Comment by masenf** [comment]
I think the pyi_generator also needs be updated to generate the stub functions, otherwise the dynamically created names aren't visible in the IDE.

**Comment by Billa05** [comment]
is this issue resolved?

**Comment by danik292** [comment]
@measenf resolved

**Comment by masenf** [comment]
This issue is still unresolved because we have to manually create entries in `reflex/components/__init__.py`. I updated the description to make it more clear what is needed here. A simple dynamic loop is not sufficient, we need code generated in real python files in order to retain good IDE integration and type checking.

**Comment by danik292** [comment]
So how to do it ? @masenf

**Comment by picklelo** [comment]
This is not needed anymore.
