### ISSUE TITLE
IP 0.0.0.0

### ISSUE THREAD

**Issue by imxade** [reflex-dev/reflex#1981]
**Describe the bug**
unable to use ip 0.0.0.0

**To Reproduce**
 put 
```sh 
api_url='http://0.0.0.0:8000'
```

**Expected behavior**
the web app should be running at http://0.0.0.0:8000 

**Specifics (please complete the following information):**
 - Python Version: 3.11
 - Reflex Version: 0.2.9
 - OS: NixOS, fedora
 - Browser (Optional): Brave
 
**edit:** not https but http

**Comment by masenf** [comment]
api_url needs to be an address that the client frontend browser can connect to. 0.0.0.0 is not a routable address from the client perspective, so it cannot find the backend.

that said, this should actually be fixed in the next release, without having to set `api_url` at all. assuming the frontend and backend are running on the same host, this will just work via #1954.

---------

i also noticed that you expect the app to be running via HTTPS... currently reflex does not do anything with TLS. If you need TLS, then our recommendation is to run the app behind a reverse proxy / load balancer like caddy or nginx.

**Comment by danisvaliev001** [comment]
`api_url='http://0.0.0.0:8000'` works fine in current version of reflex – v0.2.9

**Comment by masenf** [comment]
Fixed via https://github.com/reflex-dev/reflex/pull/2129
