### ISSUE TITLE
Native webwrapper for ios and android using cordova or capacitor.

### ISSUE THREAD

**Issue by timmypidashev** [reflex-dev/reflex#2038]
First off, major thank you to the devs for creating this project. I love that it transpiles to a nextjs project, as this enables a lot of options, and competes with modern web development while still offering the python we all know and love. Anyways, I am curious if you all have considered implementing an export to ios or android, as the this project already separates the backend from the frontend really well, allowing us to use something like [capacitor](https://github.com/ionic-team/capacitor) or cordova to automatically export the frontend to an apk or ios app. I would love to be able to have multiple builds from one codebase without having to use some old webwrapper api, and capacitor seems to do just that. I'm still a bit new to this project, but if this sounds like a great addition, I would be more than happy to submit a pr once im a bit more comfortable with reflex.

**Comment by Lendemor** [comment]
Hello,
while it would be neat to have, it's not something that is high in our priority list.
That said, if you want to work on it, feel free to do so.

Though, we'll probably have to discuss among the team if it's better to have it as a third party or part of the core.

If you have any questions, feel free to ask them here on github, or join the Discord for any discussions.

**Comment by timmypidashev** [comment]
@Lendemor Sounds good, its not a high priority on my plate either, but I am building my application with mobile deployments in mind, so later down the line some kind of integration would be nice. A any rate, I will close this issue for the time being, and once I am ready, possibly open a pr and we can go from there. Thanks for your time.

**Comment by alexandermorgan** [comment]
I was curious about this too so I ran `reflex export` and then directed capacitorjs to that built version. It seems to work on my simple anagram-solver game app as you can see in the Android Studio photo below. I didn't bother sorting out the bug that shows in the photo because this was just a test to see if this cross-platform build would work. But I think it's just because reflex seems to connect to the backend by default and I'm not running (or using) a backend for this simple app. I could maybe write out a more user-friendly list of steps if there's interest in it.

<img width="591" alt="image" src="https://github.com/reflex-dev/reflex/assets/2601689/499e9227-9d74-4252-a354-b6ed3ddcfa24">
