### ISSUE TITLE
Short-hand for clearing a form after submitting

### ISSUE THREAD

**Issue by anish-sahoo** [reflex-dev/reflex#2074]
Please create an alternative method that can set all the elements inside a form to "" after the on_submit takes place.

We used reflex in CalHacks 10.0, and this is one of the enhancements we think would be great!

**Comment by masenf** [comment]
Thanks for the suggestion. PR https://github.com/reflex-dev/reflex/pull/2012 adds the prop `reset_on_submit` which takes care of this (except it doesn't work for rx.pin_input, since that component isn't a true form field).

I also use this quite a bit:

```
class State(rx.State):
    ...
    def on_submit(self, form_data):
        # process the form
        return [rx.set_value(k, "") for k in form_data]
```

But after `reset_on_submit` lands, that wont be needed.
