### ISSUE TITLE
Bad lighthouse performance score

### ISSUE THREAD

**Issue by LouisDeconinck** [reflex-dev/reflex#2200]
I was building the tutorial app (https://reflex.dev/docs/tutorial/intro/) and was curious about the performance of Reflex.

I ran the Google Lighthouse diagnostics test which came out pretty bad, especially considering this is a very simple app. Are there any improvements that can be made on that front?

![lighthouse_1](https://github.com/reflex-dev/reflex/assets/27673665/fcf4681c-7e21-40a1-a6c5-a161de605468)
![lighthouse_2](https://github.com/reflex-dev/reflex/assets/27673665/e89ea26f-f196-4e0e-9731-729e5c2ee4a1)
![lighthouse_3](https://github.com/reflex-dev/reflex/assets/27673665/739a4511-113e-461b-a561-cdbb7b2a4c87)
![lighthouse_4](https://github.com/reflex-dev/reflex/assets/27673665/b56d5038-7515-4e56-8c2c-a4db817f9451)
![lighthouse_5](https://github.com/reflex-dev/reflex/assets/27673665/7b5b877b-fe9d-4885-a426-6581d7c2b1d7)

**Comment by masenf** [comment]
Were you running in dev mode or prod mode (`--env prod`)? I tried to reproduce this result against https://github.com/reflex-dev/reflex-chat/tree/bf80610ba1ab04cda67b6c2c8ed89c0469943150 and get the following.

Dev Mode
![image](https://github.com/reflex-dev/reflex/assets/1524005/fd458249-91c0-448a-b53d-df2692d12e71)


Prod Mode
![image](https://github.com/reflex-dev/reflex/assets/1524005/3c94e365-87bf-42de-a1d1-1ca6e990540e)



It makes a difference due to the tree-shaking and static rendering that happens when running in prod mode.
