### ISSUE TITLE
Add autocomplete support to input component

### ISSUE THREAD

**Issue by FHU-yezi** [reflex-dev/reflex#239]
When I go through the documentation of [Input](https://pynecone.io/docs/library/forms/input) component, I noticed that we should support autocomplete feature.

Just googled and found [chakra-ui-simple-autocomplete](https://www.npmjs.com/package/chakra-ui-simple-autocomplete), a Chakra UI related library licensed in MIT.

Copy the example code there:

```typescript
import { Autocomplete, Option } from 'chakra-ui-simple-autocomplete';

const options = [
  { value: 'javascript', label: 'Javascript' },
  { value: 'chakra', label: 'Chakra' },
  { value: 'react', label: 'React' },
  { value: 'css', label: 'CSS' },
];

const AutocompleteWrapper = () => {
  const [result, setResult] = React.useState<Option[]>([]);

  return (
      <Box maxW="md">
        <Autocomplete
          options={options}
          result={result}
          setResult={(options: Option[]) => setResult(options)}
          placeholder="Autocomplete"
        />
      </Box>
  );
};
```

So we should include this in our front-end build, and add some props as well as an event linstener, maybe called `on_autocomplete_selected`.

By the way, we need to give a chance that user can change `options` dynamicly, so we can query the database and change them, sounds like search component which we are working on.

**Comment by masenf** [comment]
For chakra, I think this component is more well-maintained: https://www.npmjs.com/package/@choc-ui/chakra-autocomplete

However Reflex is currently transitioning away from chakra toward radix, so I don't think we'll be taking in anymore chakra-specific components into the core. Probably this issue is on hold until Radix components are ready. Even then it's not clear exactly what functionality is needed, as "autocomplete" can be quite complex to handle in different use cases.

From the most flexible, we have things like [Downshift](https://www.downshift-js.com).

There's also a thread on the radix-ui github about adding a [ComboBox](https://github.com/radix-ui/primitives/issues/1342) primitive, that would be ideal for reflex to wrap.

Alternatively there are solutions in [shadcn/ui](https://ui.shadcn.com/docs/components/combobox) which uses [cmdk](https://github.com/pacocoursey/cmdk) under the hood

**Comment by picklelo** [comment]
We should bring this in as a third party component.
