### ISSUE TITLE
[REF-2111] ~x versus x==False gives different result

### ISSUE THREAD

**Issue by vhunyad** [reflex-dev/reflex#2761]
**Describe the bug**
I expected ~x to behave like NOT x, but it seems it gives undefined result. x==False gives correct result. It also seems to freeze frontend without error messages, I need to restart backend and open new browser tab.
BTW all frontend JS errors forces me to restart backend and open new tab, it is quite trying during development. If I remember well, this was not like this with 0.4.0, but I am not sure.

**To Reproduce**
```python
def comp() -> rx.Component:
    x=True
    return rx.vstack(
        rx.text(rx.cond(~x,"true","false")),
        rx.text(rx.cond(x==False,"true","false"))
    )
```

 - Python Version: 3.11.2
 - Reflex Version: 0.4.2
 - OS: debian 12

<sub>[REF-2111](https://linear.app/reflex-dev/issue/REF-2111/x-versus-x==false-gives-different-result)</sub>

**Comment by masenf** [comment]
Yikes here is the difference in the compiled output

```javascript
export function Text_eef7389a7d4169ca9241a296ec8b3a89() {
  return (
    <RadixThemesText as={`p`}>
      {`not x`}
      {isTrue(-2) ? `true` : `false`}
    </RadixThemesText>
  );
}

export function Text_f9aa3d5157d07f79983bbece59b54027() {
  return (
    <RadixThemesText as={`p`}>
      {`x == False`}
      {isTrue(false) ? `true` : `false`}
    </RadixThemesText>
  );
}
```

It seems that `~x` is turning the `False` into `-2`...

```python
>>> ~True
-2
```

Because `x` is just a `bool` at compile time, and not an `rx.Var`, the special override for `~` operator is not applied.

Changing the code sample provided to `x = rx.Var.create(True)` seems to produce the expected behavior.

Not sure if there is a fix in the framework that can accomodate this, but thanks for raising it and we'll consider our options.

**Comment by adhami3310** [comment]
It doesn't seem there is anything that we could do on our end. Some thoughts:

- You can force a python primitive into a Var with `rx.Var.create` as noted above, which would handle things fine. It also accepts a Var just fine, so it's safe to always pass the value to it in case it could be `int | Var`.
- If you want to use python primitives directly, use `not` instead.
