### ISSUE TITLE
Uploader with no files uploaded

### ISSUE THREAD

**Issue by Ernelene** [reflex-dev/reflex#2873]
I'm currently implementing an uploader feature and need to handle the scenario where there is an error message displayed when no files are uploaded. I'm using the rx.upload_files(upload_id=id) and rx.selected_files(id) functions, but I'm unsure how to detect when no files have been uploaded. It seems that these functions don't execute when no files are uploaded. Could you please advise on how I can check for this condition and create an error message accordingly?

**Comment by masenf** [comment]
Currently this is expected behavior given this code: https://github.com/reflex-dev/reflex/blob/ee1ff7f93fa5bfbeb48f296970977c9174fe7136/reflex/.templates/web/utils/state.js#L382-L385

The client side upload handler just returns if no files are selected for upload.

I suppose this code could be changed to still submit the request, but return an empty file list.

**Comment by Yummy-Yums** [comment]
please assign

**Comment by Yummy-Yums** [comment]
@masenf tried this and repro'd ; after clicking the upload btn , what comes through to state.js (uploadFiles ) is undefined . i logged at the call-site of* uploadFile*s and it seems 
event.payload.files
  is undefined when the user sends an "empty upload" . so it throws a parse error in the eventhandler func in uploadFiles. i think a simple log(in addition to 
return false
 to notify the user to handle this , will suffice but unless some other reason to insist on sending an empty array to the backend?

![image](https://github.com/reflex-dev/reflex/assets/77977520/21b94079-4840-4f64-9bbb-c77ac4a6ea4f)
