### ISSUE TITLE
Frontend url from config file not used

### ISSUE THREAD

**Issue by brightshadow42** [reflex-dev/reflex#3393]
Trying to deploy a Reflex app on Azure Web Apps via GitHub. 

Everything is running well but Azure log stream always shows:
`2024-05-28T17:34:44.313046931Z: [INFO]  App running at: http://localhost:3000`

Whereas rxconfig.py is set to:
```
import reflex as rx

config = rx.Config(
    app_name="chat",
    api_url="https://xxx.azurewebsites.net:8000",
    deploy_url="https://xxx.azurewebsites.net:3000",
)
```
Where `xxx` is my Azure domain. 

When visiting the Azure domain, the result is `{"detail":"Not Found"}`

Seems like the deploy_url is not correctly used or am I missing something? 
Would be most grateful for your advice. 

Running latest reflex version as of May 28th.

**Comment by masenf** [comment]
The `deploy_url` is only used for sitemap generation, so the created links point to full, accessible URLs.

The frontend will always say it's running on `localhost`, but it should be accessible externally on that port, provided that ingress/firewall is correctly configured.

The `{"detail":"Not Found"}` message is coming from the backend though, port 8000. Reflex does not have a route on the backend's root, which is why that appears. if you access the same url + `/ping` then you should see the `"pong"` message.

**Comment by brightshadow42** [comment]
Thanks for the quick response @masenf ! 

`pong` message indeed appears correctly, so how can I fix this and ensure the frontend is accessible? 
Apologies if the question is a bit broad, usually only do Swift development and still fighting my way through the web app jungle :)

**Comment by brightshadow42** [comment]
All resolved by just ignoring url config and adjusting Azure port exposure to match default reflex config.
