### ISSUE TITLE
Pynecone doesn't detect Node.js even when its installed

### ISSUE THREAD

**Issue by rohitsathish** [reflex-dev/reflex#648]
I have nodejs installed on my machine. When I run the command ```pc run``` on a conda environment, I get the following error message - 
```Node.js version 12.22.0 or higher is required to run Pynecone.```

 - Python Version:  3.10.9
 - Pynecone Version: 0.1.19
 - OS: Windows

**Comment by HellAmbro** [comment]
Check if NodeJS path is in your environment variables.
Open a command prompt and run `node` , you should see a message like this: 
`Welcome to Node.js v19.4.0.
Type ".help" for more information.`
Otherwise you must specify the `path` where the NodeJS executable is located in the Environment variables.

**Comment by rohitsathish** [comment]
This worked! Thank you

**Comment by HellAmbro** [comment]
Great, i think that this issue can be closed.
