### ISSUE TITLE
On telemetry: favor an opt-in

### ISSUE THREAD

**Issue by goanpeca** [reflex-dev/reflex#680]
Hello !

Thanks for building this awesome project.

Someone shared the project at work today and we were exploring and playing a bit with it. When reading the docs I bumped into the [telemetry section](https://pynecone.io/docs/advanced-guide/telemetry). An `opt-out` for data collection is not something I (and many others) expect in a lot of the (python) open source world.

A fellow co-worker asked: `Is a default opt-out even GDPR compliant`?

GDPR reference: https://gdpr-info.eu/

If the decision is to keep an `opt-out` telemetry, then it should be advertised clearly in many places, and not only on the advanced section of the docs. Furthermore, I would advice to include a big message when running the cli, (the `init` command for instance) so that users are aware of this and can choose to disable it before an app is even run.

However my suggestion would be to use an `opt-in`, and add this message also in the cli, with a question (y/n) to `opt-in`, so that users are aware and can choose to opt-in, and make it a default for all projects, for example.

Thanks for the conversation we had over at discord @Alek99 and the willingness to explore this. Cheers!

**Comment by Alek99** [comment]
Thanks for making this issue @goanpeca! We want to do what best for the community so would love to get everyones feedback so we can take appropriate action that best for everyone.

As a summary that telemetry is totally anonymous and we use it to only gauge general usage. We followed similar practice to NextJs and Streamlit in terms of opt out policy. 

That being said we are totally open to changing it if people feel strongly about it. We definitely do not want to turn away any users away because of this policy, and are happy to find a resolution the communities likes.
